### ISSUE TITLE
Error in skipped step

### ISSUE THREAD

**Issue by alexiel15** [allure-framework/allure-cucumber#16]
One more question!
When a scenario fails somewhere in the middle, the following steps are skipped.
But I always get an error:

```
Element 'step', attribute 'status': [facet 'enumeration'] The value 'skipped' is not an element of the set {'failed', 'broken', 'passed', 'canceled', 'pending'}.
```

**Comment by pritpalm** [comment]
Looks like I'm facing the same issue. Here is my setup information -

Allure CLI version - 2.3
allure-cucumber (0.4.4)
allure-ruby-adaptor-api (0.6.6)

When I run the test, I see following errors on command line. Though the xml is generated, when I try creating report from the xml from CLI tool I get NullPointerException. I spent whole day figuring out issue, but failed. Please help with this issue.

Element 'step', attribute 'status': [facet 'enumeration'] The value 'skipped' is
 not an element of the set {'failed', 'broken', 'passed', 'canceled', 'pending'}
.
Element 'step', attribute 'status': 'skipped' is not a valid value of the atomic
 type '{urn:model.allure.qatools.yandex.ru}status'.
Element 'step', attribute 'status': [facet 'enumeration'] The value 'skipped' is
 not an element of the set {'failed', 'broken', 'passed', 'canceled', 'pending'}

**Comment by 9ikhan** [comment]
@pritpalm  As I am on vacation I will only be able look into it next week.  Meanwhile, for quick debugging please share the stack trace of the exception and the generated xml.

**Comment by pritpalm** [comment]
Thanks 9ikhan. I'm glad to see your prompt response to my query. I love allure reports and want use it my project. But running into initial hurdles. I also wanted to know from you can it be used hudson also?

Here is xml - I dont know how to get stacktrace with ruby/cucumber. I used option -b from command line...but that didn't give me anything. If you can help me to get stacktrace, i'll do it immediately


  <?xml version="1.0" ?> 
- <ns2:test-suite xmlns="" xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1424188038725" stop="1424188063060">
  <name>Display of content for main page Based on eligibility, certain elements on the page should either be displayed or hidden. The following Scenarios have users with differing eligibility and can be used to validate the page display.</name> 
  <title>Display of content for main page Based on eligibility, certain elements on the page should either be displayed or hidden. The following Scenarios have users with differing eligibility and can be used to validate the page display.</title> 
- <test-cases>
- <test-case start="1424188038754" stop="1424188063060" status="passed">
  <name>Non-redeemable message should display Example: | non_redeemable_miles | We're sorry. You can't redeem your miles right now due to the status of your account ending in xxxx. For questions, please call the number on the back of your card. |</name> 
  <title>Non-redeemable message should display Example: | non_redeemable_miles | We're sorry. You can't redeem your miles right now due to the status of your account ending in xxxx. For questions, please call the number on the back of your card. |</title> 
- <steps>
- <step start="1424188038768" stop="1424188063060" status="skipped">
  <name>I am on the rewards homepage as a "<non_redeemable_miles>"</name> 
  <title>I am on the rewards homepage as a "<non_redeemable_miles>"</title> 
  <attachments /> 
  </step>
- <step start="1424188038783" stop="1424188063060" status="skipped">
  <name>The drawer should contain a nonredeemable <We're sorry. You can't redeem your miles right now due to the status of your account ending in xxxx. For questions, please call the number on the back of your card.></name> 
  <title>The drawer should contain a nonredeemable <We're sorry. You can't redeem your miles right now due to the status of your account ending in xxxx. For questions, please call the number on the back of your card.></title> 
  <attachments /> 
  </step>
  </steps>
  <attachments /> 
- <labels>
  <label name="severity" value="normal" /> 
  <label name="thread" value="19122336" /> 
  <label name="host" value="MUSAVA201041" /> 
  <label name="feature" value="Display of content for main page Based on eligibility, certain elements on the page should either be displayed or hidden. The following Scenarios have users with differing eligibility and can be used to validate the page display." /> 
  <label name="story" value="Non-redeemable message should display Example: | non_redeemable_miles | We're sorry. You can't redeem your miles right now due to the status of your account ending in xxxx. For questions, please call the number on the back of your card. |" /> 
  </labels>
  <parameters /> 
  </test-case>
  </test-cases>
- <labels>
  <label name="severity" value="normal" /> 
  <label name="thread" value="19122336" /> 
  <label name="host" value="MUSAVA201041" /> 
  </labels>
  </ns2:test-suite>

**Comment by pritpalm** [comment]
Thanks 9ikhan. I'm glad to see your prompt response to my query. I love allure reports and want use it my project. But running into initial hurdles. I also wanted to know from you can it be used hudson also?

I've attached xml as pic, as it would not allow me to paste xml here
![xml](https://cloud.githubusercontent.com/assets/11047015/6289621/6d4f08c0-b8ef-11e4-9d2b-4dd44204fd93.png)


- I dont know how to get stacktrace with ruby/cucumber. I used option -b from command line...but that didn't give me anything. If you can help me to get stacktrace, i'll do it immediately

**Comment by vania-pooh** [comment]
@pritpalm is this https://github.com/allure-framework/allure-jenkins-plugin what you're searching for?

**Comment by pritpalm** [comment]
I was looking for allure plugin for specifically for hudson

**Comment by pritpalm** [comment]
Hello 9ikhan, can you help me with the error?

**Comment by 9ikhan** [comment]
I just came back today. I am looking into it. Will keep you posted.

**Comment by 9ikhan** [comment]
Hi @pritpalm 

`Element 'step', attribute 'status': 'skipped' is not a valid value of the atomic
 type '{urn:model.allure.qatools.yandex.ru}status'.` This can be ignored for now. I'm rewriting the formatter and this will get fixed with it.  You would have seen it after xmls have been written. From the screenshot your xml looks to be valid.

The `NullPointerException` is thrown by Allure CLI and is unrelated to the above warning. Can you post here the console messages when this exception occurs and the command you are using to generate the report from artifacts? 

Also, as mentioned above use Allure Jenkins Plugin for use with Jenkins/Hudson CI.

I have done my testing against this [suite](https://github.com/9ikhan/wikipedia-tests) and got valid xmls and used allure CLI to generate report without any exception.

**Comment by pritpalm** [comment]
Hello @9ikhan 

Thanks for helping me out.

To generate allure report, i first navigate to the bin and execute following command -

allure --debug generate C:\05Projects\reports

C:\05Projects\reports is the folder where xml is.

Here is the debug information -

Generating report for Allure version [1.3.9]
Processing result pattern [C:\05Projects\cos_rewards\features\reports]
Found results directory [C:\05Projects\cos_rewards\features\reports]
Connection request: [route: {}->http://central][total kept alive: 0; route alloc
ated: 0 of 50; total allocated: 0 of 100]
Connection leased: [id: 0][route: {}->http://central][total kept alive: 0; route
 allocated: 1 of 50; total allocated: 1 of 100]
Connection org.apache.http.impl.conn.DefaultClientConnection@1f65e220 closed
Connection org.apache.http.impl.conn.DefaultClientConnection@1f65e220 shut down
Connection org.apache.http.impl.conn.DefaultClientConnection@1f65e220 closed
Connection released: [id: 0][route: {}->http://central][total kept alive: 0; rou
te allocated: 0 of 50; total allocated: 0 of 100]
Connection request: [route: {}->http://repo1.maven.org][total kept alive: 0; rou
te allocated: 0 of 50; total allocated: 0 of 100]
Connection leased: [id: 1][route: {}->http://repo1.maven.org][total kept alive:
0; route allocated: 1 of 50; total allocated: 1 of 100]
Connecting to repo1.maven.org:80
Connection org.apache.http.impl.conn.DefaultClientConnection@7157385e closed
Connection org.apache.http.impl.conn.DefaultClientConnection@7157385e shut down
Connection org.apache.http.impl.conn.DefaultClientConnection@7157385e closed
Connection released: [id: 1][route: {}->http://repo1.maven.org][total kept alive
: 0; route allocated: 0 of 50; total allocated: 0 of 100]
java.lang.NullPointerException
ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.NullPoin
terException

**Comment by smecsia** [comment]
@pritpalm It seems like internet connection problem. Are you using proxy or any advanced internet security options?

**Comment by pritpalm** [comment]
I had a proxy setting that i removed, open another instance of command prompt, still seeing the same error. Just to double sure, i rebooted and tried generating the report again, still getting same nulPointer Exception

**Comment by pritpalm** [comment]
@smecsia @9ikhan 

You are right, i was not able to generate this report from office, because i'm behind the firewall. But is there a way to make it work behind firewall? When I generated this report from home, it worked. But when I open the report (index.html), its says report is broken, i see following error -

Your report seems to be broken! Check out our FAQ to find a reason
Message: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/05Projects/allure%20report%20tool/bin/allure-report/templates/home.html'.
Debug: {"message":"Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/05Projects/allure%20report%20tool/bin/allure-report/templates/home.html'.","name":"NetworkError","code":19,"stack":"Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/05Projects/allure%20report%20tool/bin/allure-report/templates/home.html'.\n at Error (native)\n at file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:7978:11\n at sendReq (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:7800:9)\n at serverRequest (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:7534:16)\n at wrappedCallback (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:10930:81)\n at wrappedCallback (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:10930:81)\n at file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:11016:26\n at Scope.$eval (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:11936:28)\n at Scope.$digest (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:11762:31)\n at Scope.$apply (file:///C:/05Projects/allure%20report%20tool/bin/allure-report/vendor/angular/angular.js:12042:24)"}
![allure_error](https://cloud.githubusercontent.com/assets/11047015/6362643/7dadeada-bc5d-11e4-9135-247a29ca4c7a.png)

**Comment by 9ikhan** [comment]
Open the report in firefox.

For details read this: http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome
